// Code Generated by Sidekick is for learning and experimentation purposes only.
package com.deloitte.example.dao;

import com.deloitte.example.model.User;
import java.sql.*;

public class UserDAO {
    private Connection conn;
    public UserDAO(Connection conn) { this.conn = conn; }

    public boolean validateUser(String userId, String password) {
        String sql = "SELECT * FROM User WHERE userId = ? AND password = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, userId);
            stmt.setString(2, password);
            try (ResultSet rs = stmt.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) { e.printStackTrace(); }
        return false;
    }

    public boolean idProofExists(String idProof) {
        String sql = "SELECT * FROM User WHERE idProof = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, idProof);
            try (ResultSet rs = stmt.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) { e.printStackTrace(); }
        return false;
    }

    public boolean registerUser(User user) {
        String sql = "INSERT INTO User (userId, password, firstName, lastName, dob, mobile, idProof) VALUES (?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, user.getUserId());
            stmt.setString(2, user.getPassword());
            stmt.setString(3, user.getFirstName());
            stmt.setString(4, user.getLastName());
            stmt.setDate(5, user.getDob());
            stmt.setString(6, user.getMobile());
            stmt.setString(7, user.getIdProof());
            int rows = stmt.executeUpdate();
            return rows > 0;
        } catch (SQLException e) { e.printStackTrace(); }
        return false;
    }
}
